package com.ancao.treasures.mapper;

import com.ancao.treasures.bean.TreasuresHotlink;
import com.ancao.treasures.bean.TreasuresHotlinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TreasuresHotlinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_hotlink
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    int countByExample(TreasuresHotlinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_hotlink
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    int deleteByExample(TreasuresHotlinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_hotlink
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_hotlink
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    int insert(TreasuresHotlink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_hotlink
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    int insertSelective(TreasuresHotlink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_hotlink
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    List<TreasuresHotlink> selectByExample(TreasuresHotlinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_hotlink
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    TreasuresHotlink selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_hotlink
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") TreasuresHotlink record, @Param("example") TreasuresHotlinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_hotlink
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    int updateByExample(@Param("record") TreasuresHotlink record, @Param("example") TreasuresHotlinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_hotlink
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    int updateByPrimaryKeySelective(TreasuresHotlink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_hotlink
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    int updateByPrimaryKey(TreasuresHotlink record);
}