package com.ancao.treasures.mapper;

import com.ancao.treasures.bean.TreasuresVideo;
import com.ancao.treasures.bean.TreasuresVideoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TreasuresVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_video
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    int countByExample(TreasuresVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_video
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    int deleteByExample(TreasuresVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_video
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_video
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    int insert(TreasuresVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_video
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    int insertSelective(TreasuresVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_video
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    List<TreasuresVideo> selectByExample(TreasuresVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_video
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    TreasuresVideo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_video
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    int updateByExampleSelective(@Param("record") TreasuresVideo record, @Param("example") TreasuresVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_video
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    int updateByExample(@Param("record") TreasuresVideo record, @Param("example") TreasuresVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_video
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    int updateByPrimaryKeySelective(TreasuresVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_video
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    int updateByPrimaryKey(TreasuresVideo record);
}