package com.ancao.treasures.mapper;

import com.ancao.treasures.bean.TreasuresCodename;
import com.ancao.treasures.bean.TreasuresCodenameExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TreasuresCodenameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_codename
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    int countByExample(TreasuresCodenameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_codename
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    int deleteByExample(TreasuresCodenameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_codename
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_codename
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    int insert(TreasuresCodename record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_codename
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    int insertSelective(TreasuresCodename record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_codename
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    List<TreasuresCodename> selectByExample(TreasuresCodenameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_codename
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    TreasuresCodename selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_codename
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") TreasuresCodename record, @Param("example") TreasuresCodenameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_codename
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    int updateByExample(@Param("record") TreasuresCodename record, @Param("example") TreasuresCodenameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_codename
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    int updateByPrimaryKeySelective(TreasuresCodename record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_codename
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    int updateByPrimaryKey(TreasuresCodename record);
}