package com.ancao.treasures.mapper;

import com.ancao.treasures.bean.TreasuresOrder;
import com.ancao.treasures.bean.TreasuresOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TreasuresOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_order
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    int countByExample(TreasuresOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_order
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    int deleteByExample(TreasuresOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_order
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_order
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    int insert(TreasuresOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_order
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    int insertSelective(TreasuresOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_order
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    List<TreasuresOrder> selectByExample(TreasuresOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_order
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    TreasuresOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_order
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    int updateByExampleSelective(@Param("record") TreasuresOrder record, @Param("example") TreasuresOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_order
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    int updateByExample(@Param("record") TreasuresOrder record, @Param("example") TreasuresOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_order
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    int updateByPrimaryKeySelective(TreasuresOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treasures_order
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    int updateByPrimaryKey(TreasuresOrder record);
}