package com.ancao.treasures.bean;

public class TreasuresCodename {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_codename.id
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_codename.projectType
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    private String projecttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_codename.type
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_codename.code
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_codename.content
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_codename.description
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_codename.filed_1
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    private String filed1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_codename.id
     *
     * @return the value of treasures_codename.id
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_codename.id
     *
     * @param id the value for treasures_codename.id
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_codename.projectType
     *
     * @return the value of treasures_codename.projectType
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public String getProjecttype() {
        return projecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_codename.projectType
     *
     * @param projecttype the value for treasures_codename.projectType
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public void setProjecttype(String projecttype) {
        this.projecttype = projecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_codename.type
     *
     * @return the value of treasures_codename.type
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_codename.type
     *
     * @param type the value for treasures_codename.type
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_codename.code
     *
     * @return the value of treasures_codename.code
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_codename.code
     *
     * @param code the value for treasures_codename.code
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_codename.content
     *
     * @return the value of treasures_codename.content
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_codename.content
     *
     * @param content the value for treasures_codename.content
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_codename.description
     *
     * @return the value of treasures_codename.description
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_codename.description
     *
     * @param description the value for treasures_codename.description
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_codename.filed_1
     *
     * @return the value of treasures_codename.filed_1
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public String getFiled1() {
        return filed1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_codename.filed_1
     *
     * @param filed1 the value for treasures_codename.filed_1
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public void setFiled1(String filed1) {
        this.filed1 = filed1;
    }
}