package com.ancao.treasures.bean;

import java.util.Date;

public class TreasuresOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_order.id
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_order.out_trade_no
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_order.trade_no
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    private String tradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_order.pay_status
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    private String payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_order.userId
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_order.videoId
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    private Integer videoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_order.price
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_order.createTime
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_order.updTime
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    private Date updtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_order.id
     *
     * @return the value of treasures_order.id
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_order.id
     *
     * @param id the value for treasures_order.id
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_order.out_trade_no
     *
     * @return the value of treasures_order.out_trade_no
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_order.out_trade_no
     *
     * @param outTradeNo the value for treasures_order.out_trade_no
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_order.trade_no
     *
     * @return the value of treasures_order.trade_no
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_order.trade_no
     *
     * @param tradeNo the value for treasures_order.trade_no
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_order.pay_status
     *
     * @return the value of treasures_order.pay_status
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    public String getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_order.pay_status
     *
     * @param payStatus the value for treasures_order.pay_status
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_order.userId
     *
     * @return the value of treasures_order.userId
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_order.userId
     *
     * @param userid the value for treasures_order.userId
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_order.videoId
     *
     * @return the value of treasures_order.videoId
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    public Integer getVideoid() {
        return videoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_order.videoId
     *
     * @param videoid the value for treasures_order.videoId
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    public void setVideoid(Integer videoid) {
        this.videoid = videoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_order.price
     *
     * @return the value of treasures_order.price
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_order.price
     *
     * @param price the value for treasures_order.price
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    public void setPrice(String price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_order.createTime
     *
     * @return the value of treasures_order.createTime
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_order.createTime
     *
     * @param createtime the value for treasures_order.createTime
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_order.updTime
     *
     * @return the value of treasures_order.updTime
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    public Date getUpdtime() {
        return updtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_order.updTime
     *
     * @param updtime the value for treasures_order.updTime
     *
     * @mbggenerated Fri Jan 26 14:56:44 CST 2018
     */
    public void setUpdtime(Date updtime) {
        this.updtime = updtime;
    }
}