package com.ancao.treasures.bean;

import java.util.Date;

public class TreasuresHotlink {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_hotlink.id
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_hotlink.url
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_hotlink.projectType
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    private String projecttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_hotlink.hotNumber
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    private Integer hotnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_hotlink.description
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_hotlink.createTime
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_hotlink.updTime
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    private Date updtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_hotlink.id
     *
     * @return the value of treasures_hotlink.id
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_hotlink.id
     *
     * @param id the value for treasures_hotlink.id
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_hotlink.url
     *
     * @return the value of treasures_hotlink.url
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_hotlink.url
     *
     * @param url the value for treasures_hotlink.url
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_hotlink.projectType
     *
     * @return the value of treasures_hotlink.projectType
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public String getProjecttype() {
        return projecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_hotlink.projectType
     *
     * @param projecttype the value for treasures_hotlink.projectType
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public void setProjecttype(String projecttype) {
        this.projecttype = projecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_hotlink.hotNumber
     *
     * @return the value of treasures_hotlink.hotNumber
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public Integer getHotnumber() {
        return hotnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_hotlink.hotNumber
     *
     * @param hotnumber the value for treasures_hotlink.hotNumber
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public void setHotnumber(Integer hotnumber) {
        this.hotnumber = hotnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_hotlink.description
     *
     * @return the value of treasures_hotlink.description
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_hotlink.description
     *
     * @param description the value for treasures_hotlink.description
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_hotlink.createTime
     *
     * @return the value of treasures_hotlink.createTime
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_hotlink.createTime
     *
     * @param createtime the value for treasures_hotlink.createTime
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_hotlink.updTime
     *
     * @return the value of treasures_hotlink.updTime
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public Date getUpdtime() {
        return updtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_hotlink.updTime
     *
     * @param updtime the value for treasures_hotlink.updTime
     *
     * @mbggenerated Wed Jan 24 16:06:50 CST 2018
     */
    public void setUpdtime(Date updtime) {
        this.updtime = updtime;
    }
}