package com.ancao.treasures.bean;

import java.util.Date;

public class TreasuresUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_user.id
     *
     * @mbggenerated Thu Jan 25 14:29:36 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_user.token
     *
     * @mbggenerated Thu Jan 25 14:29:36 CST 2018
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_user.platform
     *
     * @mbggenerated Thu Jan 25 14:29:36 CST 2018
     */
    private String platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_user.version
     *
     * @mbggenerated Thu Jan 25 14:29:36 CST 2018
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_user.createTime
     *
     * @mbggenerated Thu Jan 25 14:29:36 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_user.updTime
     *
     * @mbggenerated Thu Jan 25 14:29:36 CST 2018
     */
    private Date updtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_user.id
     *
     * @return the value of treasures_user.id
     *
     * @mbggenerated Thu Jan 25 14:29:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_user.id
     *
     * @param id the value for treasures_user.id
     *
     * @mbggenerated Thu Jan 25 14:29:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_user.token
     *
     * @return the value of treasures_user.token
     *
     * @mbggenerated Thu Jan 25 14:29:36 CST 2018
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_user.token
     *
     * @param token the value for treasures_user.token
     *
     * @mbggenerated Thu Jan 25 14:29:36 CST 2018
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_user.platform
     *
     * @return the value of treasures_user.platform
     *
     * @mbggenerated Thu Jan 25 14:29:36 CST 2018
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_user.platform
     *
     * @param platform the value for treasures_user.platform
     *
     * @mbggenerated Thu Jan 25 14:29:36 CST 2018
     */
    public void setPlatform(String platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_user.version
     *
     * @return the value of treasures_user.version
     *
     * @mbggenerated Thu Jan 25 14:29:36 CST 2018
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_user.version
     *
     * @param version the value for treasures_user.version
     *
     * @mbggenerated Thu Jan 25 14:29:36 CST 2018
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_user.createTime
     *
     * @return the value of treasures_user.createTime
     *
     * @mbggenerated Thu Jan 25 14:29:36 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_user.createTime
     *
     * @param createtime the value for treasures_user.createTime
     *
     * @mbggenerated Thu Jan 25 14:29:36 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_user.updTime
     *
     * @return the value of treasures_user.updTime
     *
     * @mbggenerated Thu Jan 25 14:29:36 CST 2018
     */
    public Date getUpdtime() {
        return updtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_user.updTime
     *
     * @param updtime the value for treasures_user.updTime
     *
     * @mbggenerated Thu Jan 25 14:29:36 CST 2018
     */
    public void setUpdtime(Date updtime) {
        this.updtime = updtime;
    }
}