package com.ancao.treasures.bean;

import java.util.Date;

public class TreasuresVideo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_video.id
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_video.projectType
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    private String projecttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_video.type
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_video.webType
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    private String webtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_video.name
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_video.sort
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    private String sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_video.price
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_video.videoUrl
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    private String videourl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_video.jointUrl
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    private String jointurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_video.videoTime
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    private String videotime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_video.vip
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    private String vip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_video.videoFlag
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    private String videoflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_video.imgUrl
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_video.description
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_video.webUrl
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    private String weburl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_video.createTime
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treasures_video.updTime
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    private Date updtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_video.id
     *
     * @return the value of treasures_video.id
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_video.id
     *
     * @param id the value for treasures_video.id
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_video.projectType
     *
     * @return the value of treasures_video.projectType
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public String getProjecttype() {
        return projecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_video.projectType
     *
     * @param projecttype the value for treasures_video.projectType
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public void setProjecttype(String projecttype) {
        this.projecttype = projecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_video.type
     *
     * @return the value of treasures_video.type
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_video.type
     *
     * @param type the value for treasures_video.type
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_video.webType
     *
     * @return the value of treasures_video.webType
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public String getWebtype() {
        return webtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_video.webType
     *
     * @param webtype the value for treasures_video.webType
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public void setWebtype(String webtype) {
        this.webtype = webtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_video.name
     *
     * @return the value of treasures_video.name
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_video.name
     *
     * @param name the value for treasures_video.name
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_video.sort
     *
     * @return the value of treasures_video.sort
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_video.sort
     *
     * @param sort the value for treasures_video.sort
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public void setSort(String sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_video.price
     *
     * @return the value of treasures_video.price
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_video.price
     *
     * @param price the value for treasures_video.price
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public void setPrice(String price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_video.videoUrl
     *
     * @return the value of treasures_video.videoUrl
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public String getVideourl() {
        return videourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_video.videoUrl
     *
     * @param videourl the value for treasures_video.videoUrl
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public void setVideourl(String videourl) {
        this.videourl = videourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_video.jointUrl
     *
     * @return the value of treasures_video.jointUrl
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public String getJointurl() {
        return jointurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_video.jointUrl
     *
     * @param jointurl the value for treasures_video.jointUrl
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public void setJointurl(String jointurl) {
        this.jointurl = jointurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_video.videoTime
     *
     * @return the value of treasures_video.videoTime
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public String getVideotime() {
        return videotime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_video.videoTime
     *
     * @param videotime the value for treasures_video.videoTime
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public void setVideotime(String videotime) {
        this.videotime = videotime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_video.vip
     *
     * @return the value of treasures_video.vip
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public String getVip() {
        return vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_video.vip
     *
     * @param vip the value for treasures_video.vip
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public void setVip(String vip) {
        this.vip = vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_video.videoFlag
     *
     * @return the value of treasures_video.videoFlag
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public String getVideoflag() {
        return videoflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_video.videoFlag
     *
     * @param videoflag the value for treasures_video.videoFlag
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public void setVideoflag(String videoflag) {
        this.videoflag = videoflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_video.imgUrl
     *
     * @return the value of treasures_video.imgUrl
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_video.imgUrl
     *
     * @param imgurl the value for treasures_video.imgUrl
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_video.description
     *
     * @return the value of treasures_video.description
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_video.description
     *
     * @param description the value for treasures_video.description
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_video.webUrl
     *
     * @return the value of treasures_video.webUrl
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public String getWeburl() {
        return weburl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_video.webUrl
     *
     * @param weburl the value for treasures_video.webUrl
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public void setWeburl(String weburl) {
        this.weburl = weburl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_video.createTime
     *
     * @return the value of treasures_video.createTime
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_video.createTime
     *
     * @param createtime the value for treasures_video.createTime
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treasures_video.updTime
     *
     * @return the value of treasures_video.updTime
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public Date getUpdtime() {
        return updtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treasures_video.updTime
     *
     * @param updtime the value for treasures_video.updTime
     *
     * @mbggenerated Fri Jun 01 10:04:48 CST 2018
     */
    public void setUpdtime(Date updtime) {
        this.updtime = updtime;
    }
}